spring:
  application:
    name: therasync-clients
  datasource:
    url: jdbc:postgresql://localhost:5432/therasync_main
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081
